// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppDrawer: typeof import('./src/components/global/AppDrawer.vue')['default']
    AppToolbar: typeof import('./src/components/global/AppToolbar.vue')['default']
    BottomSheet: typeof import('./src/components/global/BottomSheet.vue')['default']
    BrandPage: typeof import('./src/pages/LandingPages/BrandPage.vue')['default']
    ErrorNotFound: typeof import('./src/pages/ErrorNotFound.vue')['default']
    GlobalCarousel: typeof import('./src/components/global/GlobalCarousel.vue')['default']
    IndexPage: typeof import('./src/pages/IndexPage.vue')['default']
    LinearLoadingBar: typeof import('./src/components/global/LinearLoadingBar.vue')['default']
    LoginForm: typeof import('./src/components/authentication/LoginForm.vue')['default']
    MainLayout: typeof import('./src/layouts/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
